services:
  webapi:
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=EgeYurtGrupDB;User Id=sa;Password=EgeYurt2024!;TrustServerCertificate=True
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=EgeYurt2024!
    ports:
      - "1433:1433"
