// <auto-generated />
using Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DBConnection))]
    [Migration("20241002114605_frstMig")]
    partial class frstMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.UserClaimModels.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("Core.Entities.UserClaimModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            IsActive = true,
                            LastName = "admin",
                            PasswordHash = new byte[] { 233, 161, 183, 192, 221, 240, 153, 35, 64, 47, 17, 92, 127, 204, 17, 145, 187, 63, 137, 126, 47, 33, 136, 115, 62, 90, 82, 247, 4, 59, 180, 206, 188, 248, 2, 254, 123, 99, 95, 153, 86, 30, 8, 186, 118, 148, 185, 238, 125, 22, 196, 180, 158, 3, 146, 231, 240, 95, 151, 54, 36, 228, 39, 206 },
                            PasswordSalt = new byte[] { 197, 17, 3, 157, 160, 38, 75, 94, 114, 112, 59, 28, 184, 168, 96, 79, 39, 122, 115, 24, 82, 177, 41, 204, 117, 88, 23, 156, 205, 227, 133, 7, 157, 247, 218, 128, 74, 61, 114, 85, 247, 200, 175, 69, 80, 229, 71, 30, 113, 228, 192, 203, 47, 17, 184, 42, 77, 41, 70, 92, 76, 174, 167, 126, 3, 38, 248, 145, 4, 232, 230, 109, 22, 26, 241, 197, 46, 171, 234, 239, 19, 229, 113, 6, 58, 72, 60, 200, 140, 213, 207, 57, 107, 124, 81, 128, 4, 237, 19, 120, 86, 74, 178, 232, 117, 200, 164, 220, 151, 34, 5, 72, 225, 134, 142, 118, 115, 134, 187, 87, 226, 162, 202, 64, 145, 198, 190, 245 }
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@gmail.com",
                            FirstName = "user",
                            IsActive = true,
                            LastName = "user",
                            PasswordHash = new byte[] { 187, 26, 51, 6, 209, 9, 193, 85, 92, 79, 49, 72, 137, 250, 87, 86, 103, 31, 7, 147, 162, 185, 211, 57, 143, 117, 236, 186, 231, 28, 233, 148, 102, 27, 24, 244, 178, 34, 194, 66, 25, 200, 136, 31, 47, 104, 217, 83, 85, 253, 169, 197, 155, 98, 86, 138, 31, 59, 17, 135, 206, 69, 102, 173 },
                            PasswordSalt = new byte[] { 2, 15, 137, 75, 2, 234, 79, 147, 181, 126, 204, 64, 24, 120, 150, 175, 168, 156, 171, 1, 207, 250, 172, 198, 71, 81, 58, 39, 249, 213, 212, 205, 25, 48, 215, 211, 195, 25, 162, 151, 229, 14, 116, 93, 70, 157, 212, 239, 242, 105, 15, 84, 0, 241, 140, 205, 61, 214, 177, 123, 88, 96, 233, 12, 178, 103, 30, 152, 72, 15, 230, 243, 5, 176, 95, 1, 229, 224, 113, 180, 131, 112, 30, 123, 59, 246, 3, 163, 254, 153, 31, 181, 69, 81, 95, 197, 240, 41, 127, 248, 86, 250, 103, 20, 155, 211, 162, 119, 6, 239, 2, 161, 238, 106, 117, 134, 213, 0, 61, 118, 148, 188, 43, 167, 87, 183, 81, 102 }
                        });
                });

            modelBuilder.Entity("Core.Entities.UserClaimModels.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperationClaimId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AuthorName");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("BookName");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("PrintingHouse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Carl Sagan",
                            BookName = "Cosmos",
                            Image = "http://localhost:5000/images/b4c2e771-0c0c-4287-9301-5dae7728ebec.jpg",
                            Price = 18m,
                            PrintingHouse = "Premius Yayın Evi"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Stephen W. Hawking",
                            BookName = "The Theory Of Everything",
                            Image = "http://localhost:5000/images/516a5d15-6bb5-4428-a574-421a111e5017.jpg",
                            Price = 8m,
                            PrintingHouse = "Premius Yayın Evi"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Victor Hugo",
                            BookName = "Notre Dame'in Kamburu",
                            Image = "http://localhost:5000/images/a208ba3f-79d5-49e2-b3e1-7d6b9aafb2db.jpg",
                            Price = 10m,
                            PrintingHouse = "Kültür Yayın Evi"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Wulf Dorn",
                            BookName = "Şizofren",
                            Image = "http://localhost:5000/images/c2df2671-66de-44d3-af88-b9b7981b95e8.jpg",
                            Price = 14m,
                            PrintingHouse = "Pegasus Yayıncılık"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Paulo Coelho",
                            BookName = "Simyacı",
                            Image = "http://localhost:5000/images/1b52d6bd-0b73-4937-a84a-217d859cad74.jpg",
                            Price = 3m,
                            PrintingHouse = "Pegasus Yayıncılık"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Robin Sharma",
                            BookName = "Ferrari'sini Satan Bilge",
                            Image = "http://localhost:5000/images/94fc2ab3-5398-4288-a01a-1847625dd739.jpg",
                            Price = 14m,
                            PrintingHouse = "Pegasus Yayıncılık"
                        });
                });

            modelBuilder.Entity("Core.Entities.UserClaimModels.UserOperationClaim", b =>
                {
                    b.HasOne("Core.Entities.UserClaimModels.OperationClaim", null)
                        .WithMany()
                        .HasForeignKey("OperationClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserClaimModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
